### PR TITLE
DMO-74 push "master" and "latest" when branch is master

### PR DESCRIPTION
**Pull request by xeger**

### CODE REVIEW

**Comment by crunis** [comment]
Since TravisCI directly clones the repo using `--branch=xxxx --depth=50`, the default branch is unknown and the git command fails:
```
$ git branch -r
origin/crunis_test
$ git branch -r --points-at refs/remotes/origin/HEAD
error: malformed object name 'refs/remotes/origin/HEAD'
```
We probably can use this fact to know we are not in the default branch, I'll add a commit soon.

**Comment by xeger** [comment]
Argh! Based on your other commit, tho, we can't use `--points-at` anyway. :(

Ah well; it was a nice piece of flair. We can just assume default branch is master, as you've done. That will be accurate for any repo except `ci` itself (amusingly!) and `ci` doesn't use its own script to build itself.

**Comment by crunis** [comment]
What do you think about my last (6a58a0a) commit? It makes the trick but I'm afraid it may be overcomplicated for the few cases that the default branch is not master.

**Comment by crunis** [comment]
Something like this ? Don't merge yet, I'll like to run some tests

**Comment by xeger** [comment]
Yup! Simple but effective.

**Comment by crunis** [comment]
Fully tested. Merging

**Pull request merged**
